extensions:
        health_check:
        zpages:
                endpoint: 0.0.0.0:55679
receivers:
        prometheus:
                config:
                        scrape_configs:
                                - job_name: 'otel_collector'
                                  scrape_interval: 10s
                                  static_configs:
                                          - targets: ['localhost:8083']
processors:
        batch:
        queued_retry:
exporters:
        stackdriver:
                project: "otel-gce-metrics"
service:
        pipelines:
                metrics:
                        receivers: [prometheus]
                        exporters: [stackdriver]
        extensions: [health_check, zpages]